set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_TRIPLE "x86_64-w64-mingw32")
if(DEFINED ENV{MINGW_TRIPLE})
  set(MINGW_TRIPLE "$ENV{MINGW_TRIPLE}")
endif()

set(MINGW_SYSROOT "")
if(DEFINED ENV{MINGW_SYSROOT})
  set(MINGW_SYSROOT "$ENV{MINGW_SYSROOT}")
endif()
if(MINGW_SYSROOT STREQUAL "")
  set(MINGW_SYSROOT "/opt/homebrew/opt/mingw-w64/toolchain-x86_64/${MINGW_TRIPLE}")
endif()

set(CMAKE_C_COMPILER "${MINGW_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${MINGW_TRIPLE}-g++")
set(CMAKE_RC_COMPILER "${MINGW_TRIPLE}-windres")

if(EXISTS "${MINGW_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH "${MINGW_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
